# Generated by Django 2.2.16 on 2023-01-23 06:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0009_auto_20230123_0910"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="follow",
            options={
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("user", "author")},
        ),
    ]
