# Generated by Django 2.2.16 on 2023-01-23 06:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0011_auto_20230123_0927"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="follow",
            name="unique_following",
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("user", "author")},
        ),
    ]
